// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rwUYFoLZwHEqYodpMb7shh
// Component: tvb57mWHpJ
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_app_starter.module.css"; // plasmic-import: rwUYFoLZwHEqYodpMb7shh/projectcss
import sty from "./PlasmicCompanies.module.css"; // plasmic-import: tvb57mWHpJ/css
import AddCircleIcon from "./icons/PlasmicIcon__AddCircle"; // plasmic-import: pQzXXZlx2h/icon
import _16OutlinedSuggestedSymbolPlusIcon from "./icons/PlasmicIcon___16OutlinedSuggestedSymbolPlus"; // plasmic-import: SyCyX9SFfw/icon
import IconsArrowRight26Icon from "./icons/PlasmicIcon__IconsArrowRight26"; // plasmic-import: H_zFdTIsw5/icon
import ScrollIcon from "./icons/PlasmicIcon__Scroll"; // plasmic-import: _Zb3CJ77Bh/icon
import MinusCirlceIcon from "./icons/PlasmicIcon__MinusCirlce"; // plasmic-import: Z7G4Kqox3J/icon
import FilterIcon from "./icons/PlasmicIcon__Filter"; // plasmic-import: iK-DyEMsNn/icon
import CloseIcon from "./icons/PlasmicIcon__Close"; // plasmic-import: k88yuAzpGQ/icon
import ArrowDownIcon from "./icons/PlasmicIcon__ArrowDown"; // plasmic-import: HKpwktpdqJ/icon
import AccessIcon from "./icons/PlasmicIcon__Access"; // plasmic-import: _E9oRijXyt/icon
import ManagementIcon from "./icons/PlasmicIcon__Management"; // plasmic-import: 6vnGG566lG/icon
import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: zTYEIFxNn9/icon
import IconsBellIcon from "./icons/PlasmicIcon__IconsBell"; // plasmic-import: AZSbFXcbB4/icon
import CategoryIcon from "./icons/PlasmicIcon__Category"; // plasmic-import: ot7TCVEE4C/icon
import SearchIcon from "./icons/PlasmicIcon__Search"; // plasmic-import: zkBoT91IcW8/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: CoRzsksBt9_/icon
import group4GtVffIgVaj from "./images/group4.svg"; // plasmic-import: gtVFFIgVAJ/picture
import group5Miq1XqTfD from "./images/group5.svg"; // plasmic-import: -MIQ1XQTfD/picture

export const PlasmicCompanies__VariantProps = new Array();

export const PlasmicCompanies__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicCompanies__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <div
              data-plasmic-name={"companies"}
              data-plasmic-override={overrides.companies}
              className={classNames(projectcss.all, sty.companies)}
            >
              <div
                data-plasmic-name={"list"}
                data-plasmic-override={overrides.list}
                className={classNames(projectcss.all, sty.list)}
              >
                <div
                  data-plasmic-name={"_6"}
                  data-plasmic-override={overrides._6}
                  className={classNames(projectcss.all, sty._6)}
                >
                  <div
                    data-plasmic-name={"rectangle104"}
                    data-plasmic-override={overrides.rectangle104}
                    className={classNames(projectcss.all, sty.rectangle104)}
                  />

                  <div
                    data-plasmic-name={"vuesaxlinearaddCircle"}
                    data-plasmic-override={overrides.vuesaxlinearaddCircle}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearaddCircle
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxlinearaddCircle2"}
                      data-plasmic-override={overrides.vuesaxlinearaddCircle2}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxlinearaddCircle2
                      )}
                    >
                      <AddCircleIcon
                        className={classNames(projectcss.all, sty.svg__a0SQc)}
                        role={"img"}
                      />
                    </div>
                  </div>
                  {false ? (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"dataDisplayCheckbox"}
                      data-plasmic-override={overrides.dataDisplayCheckbox}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.dataDisplayCheckbox
                      )}
                    >
                      <div
                        data-plasmic-name={"group731"}
                        data-plasmic-override={overrides.group731}
                        className={classNames(projectcss.all, sty.group731)}
                      >
                        <div
                          data-plasmic-name={"rectangle117"}
                          data-plasmic-override={overrides.rectangle117}
                          className={classNames(
                            projectcss.all,
                            sty.rectangle117
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1R0Qp
                          )}
                        >
                          {"\uf00c"}
                        </div>
                      </div>
                    </p.Stack>
                  ) : null}
                  <div
                    data-plasmic-name={"_24January2022"}
                    data-plasmic-override={overrides._24January2022}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2022
                    )}
                  >
                    {"Feeney, Rohan and Herman"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2023"}
                    data-plasmic-override={overrides._24January2023}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2023
                    )}
                  >
                    {"Lagos, Nigeria"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2025"}
                    data-plasmic-override={overrides._24January2025}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2025
                    )}
                  >
                    {"Nigerian Naira"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2024"}
                    data-plasmic-override={overrides._24January2024}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2024
                    )}
                  >
                    {"01-01-2020"}
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tagGreen"}
                    data-plasmic-override={overrides.tagGreen}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tagGreen)}
                  >
                    <div
                      data-plasmic-name={"live"}
                      data-plasmic-override={overrides.live}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.live
                      )}
                    >
                      {"Inactive"}
                    </div>
                  </p.Stack>
                </div>
                <div
                  data-plasmic-name={"_5"}
                  data-plasmic-override={overrides._5}
                  className={classNames(projectcss.all, sty._5)}
                >
                  <div
                    data-plasmic-name={"rectangle105"}
                    data-plasmic-override={overrides.rectangle105}
                    className={classNames(projectcss.all, sty.rectangle105)}
                  />

                  <div
                    data-plasmic-name={"vuesaxlinearaddCircle3"}
                    data-plasmic-override={overrides.vuesaxlinearaddCircle3}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearaddCircle3
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxlinearaddCircle4"}
                      data-plasmic-override={overrides.vuesaxlinearaddCircle4}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxlinearaddCircle4
                      )}
                    >
                      <AddCircleIcon
                        className={classNames(projectcss.all, sty.svg___4AtxX)}
                        role={"img"}
                      />
                    </div>
                  </div>
                  {false ? (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"dataDisplayCheckbox2"}
                      data-plasmic-override={overrides.dataDisplayCheckbox2}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.dataDisplayCheckbox2
                      )}
                    >
                      <div
                        data-plasmic-name={"group732"}
                        data-plasmic-override={overrides.group732}
                        className={classNames(projectcss.all, sty.group732)}
                      >
                        <div
                          data-plasmic-name={"rectangle110"}
                          data-plasmic-override={overrides.rectangle110}
                          className={classNames(
                            projectcss.all,
                            sty.rectangle110
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tQpW
                          )}
                        >
                          {"\uf00c"}
                        </div>
                      </div>
                    </p.Stack>
                  ) : null}
                  <div
                    data-plasmic-name={"_24January2026"}
                    data-plasmic-override={overrides._24January2026}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2026
                    )}
                  >
                    {"Osinski, Nader and Cruickshank"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2027"}
                    data-plasmic-override={overrides._24January2027}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2027
                    )}
                  >
                    {"Lagos, Nigeria"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2028"}
                    data-plasmic-override={overrides._24January2028}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2028
                    )}
                  >
                    {"Nigerian Naira"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2029"}
                    data-plasmic-override={overrides._24January2029}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2029
                    )}
                  >
                    {"01-01-2020"}
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tagGreen2"}
                    data-plasmic-override={overrides.tagGreen2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tagGreen2)}
                  >
                    <div
                      data-plasmic-name={"live2"}
                      data-plasmic-override={overrides.live2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.live2
                      )}
                    >
                      {"Active"}
                    </div>
                  </p.Stack>
                </div>
                <div
                  data-plasmic-name={"_4"}
                  data-plasmic-override={overrides._4}
                  className={classNames(projectcss.all, sty._4)}
                >
                  <div
                    data-plasmic-name={"rectangle106"}
                    data-plasmic-override={overrides.rectangle106}
                    className={classNames(projectcss.all, sty.rectangle106)}
                  />

                  {false ? (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"dataDisplayCheckbox3"}
                      data-plasmic-override={overrides.dataDisplayCheckbox3}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.dataDisplayCheckbox3
                      )}
                    >
                      <div
                        data-plasmic-name={"group733"}
                        data-plasmic-override={overrides.group733}
                        className={classNames(projectcss.all, sty.group733)}
                      >
                        <div
                          data-plasmic-name={"rectangle111"}
                          data-plasmic-override={overrides.rectangle111}
                          className={classNames(
                            projectcss.all,
                            sty.rectangle111
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hx5Zw
                          )}
                        >
                          {"\uf00c"}
                        </div>
                      </div>
                    </p.Stack>
                  ) : null}
                  <div
                    data-plasmic-name={"_24January2030"}
                    data-plasmic-override={overrides._24January2030}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2030
                    )}
                  >
                    {"Holistic Oil & Gas"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2031"}
                    data-plasmic-override={overrides._24January2031}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2031
                    )}
                  >
                    {"Lagos, Nigeria"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2032"}
                    data-plasmic-override={overrides._24January2032}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2032
                    )}
                  >
                    {"Nigerian Naira"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2033"}
                    data-plasmic-override={overrides._24January2033}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2033
                    )}
                  >
                    {"01-01-2020"}
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tagGreen3"}
                    data-plasmic-override={overrides.tagGreen3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tagGreen3)}
                  >
                    <div
                      data-plasmic-name={"live3"}
                      data-plasmic-override={overrides.live3}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.live3
                      )}
                    >
                      {"Active"}
                    </div>
                  </p.Stack>
                  <div
                    data-plasmic-name={"vuesaxlinearaddCircle5"}
                    data-plasmic-override={overrides.vuesaxlinearaddCircle5}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearaddCircle5
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxlinearaddCircle6"}
                      data-plasmic-override={overrides.vuesaxlinearaddCircle6}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxlinearaddCircle6
                      )}
                    >
                      <AddCircleIcon
                        className={classNames(projectcss.all, sty.svg__nibW)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"_3"}
                  data-plasmic-override={overrides._3}
                  className={classNames(projectcss.all, sty._3)}
                >
                  <div
                    data-plasmic-name={"rectangle118"}
                    data-plasmic-override={overrides.rectangle118}
                    className={classNames(projectcss.all, sty.rectangle118)}
                  />

                  <div
                    data-plasmic-name={"vuesaxlinearaddCircle7"}
                    data-plasmic-override={overrides.vuesaxlinearaddCircle7}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearaddCircle7
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxlinearaddCircle8"}
                      data-plasmic-override={overrides.vuesaxlinearaddCircle8}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxlinearaddCircle8
                      )}
                    >
                      <AddCircleIcon
                        className={classNames(projectcss.all, sty.svg__fqc2R)}
                        role={"img"}
                      />
                    </div>
                  </div>
                  {false ? (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"dataDisplayCheckbox4"}
                      data-plasmic-override={overrides.dataDisplayCheckbox4}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.dataDisplayCheckbox4
                      )}
                    >
                      <div
                        data-plasmic-name={"group734"}
                        data-plasmic-override={overrides.group734}
                        className={classNames(projectcss.all, sty.group734)}
                      >
                        <div
                          data-plasmic-name={"rectangle112"}
                          data-plasmic-override={overrides.rectangle112}
                          className={classNames(
                            projectcss.all,
                            sty.rectangle112
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__duWwv
                          )}
                        >
                          {"\uf00c"}
                        </div>
                      </div>
                    </p.Stack>
                  ) : null}
                  <div
                    data-plasmic-name={"_24January2034"}
                    data-plasmic-override={overrides._24January2034}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2034
                    )}
                  >
                    {"Feeney, Rohan and Herman"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2035"}
                    data-plasmic-override={overrides._24January2035}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2035
                    )}
                  >
                    {"Lagos, Nigeria"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2036"}
                    data-plasmic-override={overrides._24January2036}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2036
                    )}
                  >
                    {"Nigerian Naira"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2037"}
                    data-plasmic-override={overrides._24January2037}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2037
                    )}
                  >
                    {"01-01-2020"}
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tagGreen4"}
                    data-plasmic-override={overrides.tagGreen4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tagGreen4)}
                  >
                    <div
                      data-plasmic-name={"live4"}
                      data-plasmic-override={overrides.live4}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.live4
                      )}
                    >
                      {"Inactive"}
                    </div>
                  </p.Stack>
                </div>
                <div
                  data-plasmic-name={"_2"}
                  data-plasmic-override={overrides._2}
                  className={classNames(projectcss.all, sty._2)}
                >
                  <div
                    data-plasmic-name={"rectangle119"}
                    data-plasmic-override={overrides.rectangle119}
                    className={classNames(projectcss.all, sty.rectangle119)}
                  />

                  <div
                    data-plasmic-name={"vuesaxlinearaddCircle9"}
                    data-plasmic-override={overrides.vuesaxlinearaddCircle9}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearaddCircle9
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxlinearaddCircle10"}
                      data-plasmic-override={overrides.vuesaxlinearaddCircle10}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxlinearaddCircle10
                      )}
                    >
                      <AddCircleIcon
                        className={classNames(projectcss.all, sty.svg___5TBAj)}
                        role={"img"}
                      />
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"_24January2038"}
                    data-plasmic-override={overrides._24January2038}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2038
                    )}
                  >
                    {"Osinski, Nader and Cruickshank"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2039"}
                    data-plasmic-override={overrides._24January2039}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2039
                    )}
                  >
                    {"Lagos, Nigeria"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2040"}
                    data-plasmic-override={overrides._24January2040}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2040
                    )}
                  >
                    {"Nigerian Naira"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2041"}
                    data-plasmic-override={overrides._24January2041}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2041
                    )}
                  >
                    {"01-01-2020"}
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tagGreen5"}
                    data-plasmic-override={overrides.tagGreen5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tagGreen5)}
                  >
                    <div
                      data-plasmic-name={"live5"}
                      data-plasmic-override={overrides.live5}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.live5
                      )}
                    >
                      {"Active"}
                    </div>
                  </p.Stack>
                </div>
                <div
                  data-plasmic-name={"_1"}
                  data-plasmic-override={overrides._1}
                  className={classNames(projectcss.all, sty._1)}
                >
                  <div
                    data-plasmic-name={"rectangle113"}
                    data-plasmic-override={overrides.rectangle113}
                    className={classNames(projectcss.all, sty.rectangle113)}
                  />

                  {false ? (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"dataDisplayCheckbox5"}
                      data-plasmic-override={overrides.dataDisplayCheckbox5}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.dataDisplayCheckbox5
                      )}
                    >
                      <div
                        data-plasmic-name={"group735"}
                        data-plasmic-override={overrides.group735}
                        className={classNames(projectcss.all, sty.group735)}
                      >
                        <div
                          data-plasmic-name={"rectangle114"}
                          data-plasmic-override={overrides.rectangle114}
                          className={classNames(
                            projectcss.all,
                            sty.rectangle114
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fyhBy
                          )}
                        >
                          {"\uf00c"}
                        </div>
                      </div>
                    </p.Stack>
                  ) : null}
                  <div
                    data-plasmic-name={"_24January2042"}
                    data-plasmic-override={overrides._24January2042}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2042
                    )}
                  >
                    {"Holistic Oil & Gas"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2043"}
                    data-plasmic-override={overrides._24January2043}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2043
                    )}
                  >
                    {"Lagos, Nigeria"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2044"}
                    data-plasmic-override={overrides._24January2044}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2044
                    )}
                  >
                    {"Nigerian Naira"}
                  </div>
                  <div
                    data-plasmic-name={"_24January2045"}
                    data-plasmic-override={overrides._24January2045}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty._24January2045
                    )}
                  >
                    {"01-01-2020"}
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame36152"}
                    data-plasmic-override={overrides.frame36152}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame36152)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"tagBlue"}
                      data-plasmic-override={overrides.tagBlue}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.tagBlue)}
                    >
                      <div
                        data-plasmic-name={"inventoryDemo"}
                        data-plasmic-override={overrides.inventoryDemo}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.inventoryDemo
                        )}
                      >
                        {"Finas"}
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"tagBlue2"}
                      data-plasmic-override={overrides.tagBlue2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.tagBlue2)}
                    >
                      <div
                        data-plasmic-name={"inventoryDemo2"}
                        data-plasmic-override={overrides.inventoryDemo2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.inventoryDemo2
                        )}
                      >
                        {"HRMS"}
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"tagBlue3"}
                      data-plasmic-override={overrides.tagBlue3}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.tagBlue3)}
                    >
                      <div
                        data-plasmic-name={"inventoryDemo3"}
                        data-plasmic-override={overrides.inventoryDemo3}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.inventoryDemo3
                        )}
                      >
                        {"Sales"}
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"tagBlue4"}
                      data-plasmic-override={overrides.tagBlue4}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.tagBlue4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oPlW5
                        )}
                      >
                        {"Inventory - Demo"}
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"tagBlue5"}
                      data-plasmic-override={overrides.tagBlue5}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.tagBlue5)}
                    >
                      <div
                        data-plasmic-name={"inventoryDemo4"}
                        data-plasmic-override={overrides.inventoryDemo4}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.inventoryDemo4
                        )}
                      >
                        {"Procurement"}
                      </div>
                    </p.Stack>
                    {false ? (
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"secondaryButtonSmall"}
                        data-plasmic-override={overrides.secondaryButtonSmall}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.secondaryButtonSmall
                        )}
                      >
                        {false ? (
                          <_16OutlinedSuggestedSymbolPlusIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___2Srtt
                            )}
                            role={"img"}
                          />
                        ) : null}
                        <div
                          data-plasmic-name={"button"}
                          data-plasmic-override={overrides.button}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.button
                          )}
                        >
                          {"+3"}
                        </div>
                        {false ? (
                          <IconsArrowRight26Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rb1Ef
                            )}
                            role={"img"}
                          />
                        ) : null}
                      </p.Stack>
                    ) : null}
                    <div
                      data-plasmic-name={"frame36247"}
                      data-plasmic-override={overrides.frame36247}
                      className={classNames(projectcss.all, sty.frame36247)}
                    >
                      <div
                        data-plasmic-name={"vuesaxlinearscroll"}
                        data-plasmic-override={overrides.vuesaxlinearscroll}
                        className={classNames(
                          projectcss.all,
                          sty.vuesaxlinearscroll
                        )}
                      >
                        <ScrollIcon
                          className={classNames(projectcss.all, sty.svg__gtSwo)}
                          role={"img"}
                        />
                      </div>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tagGreen6"}
                    data-plasmic-override={overrides.tagGreen6}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tagGreen6)}
                  >
                    <div
                      data-plasmic-name={"live6"}
                      data-plasmic-override={overrides.live6}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.live6
                      )}
                    >
                      {"Active"}
                    </div>
                  </p.Stack>
                  <div
                    data-plasmic-name={"vuesaxlinearminusCirlce"}
                    data-plasmic-override={overrides.vuesaxlinearminusCirlce}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearminusCirlce
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxlinearminusCirlce2"}
                      data-plasmic-override={overrides.vuesaxlinearminusCirlce2}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxlinearminusCirlce2
                      )}
                    >
                      <MinusCirlceIcon
                        className={classNames(projectcss.all, sty.svg__nD92)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"top"}
                data-plasmic-override={overrides.top}
                className={classNames(projectcss.all, sty.top)}
              >
                <div
                  data-plasmic-name={"rectangle103"}
                  data-plasmic-override={overrides.rectangle103}
                  className={classNames(projectcss.all, sty.rectangle103)}
                />

                <div
                  data-plasmic-name={"_24January2046"}
                  data-plasmic-override={overrides._24January2046}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._24January2046
                  )}
                >
                  {"Name"}
                </div>
                <div
                  data-plasmic-name={"_24January2047"}
                  data-plasmic-override={overrides._24January2047}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._24January2047
                  )}
                >
                  {"Location"}
                </div>
                <div
                  data-plasmic-name={"_24January2048"}
                  data-plasmic-override={overrides._24January2048}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._24January2048
                  )}
                >
                  {"Base Currency"}
                </div>
                <div
                  data-plasmic-name={"_24January2049"}
                  data-plasmic-override={overrides._24January2049}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._24January2049
                  )}
                >
                  {"On Boarding"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vyZnr
                  )}
                >
                  {"Status"}
                </div>
              </div>
              <p.Stack
                as={"div"}
                data-plasmic-name={"footer2"}
                data-plasmic-override={overrides.footer2}
                hasGap={true}
                className={classNames(projectcss.all, sty.footer2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eFTm
                  )}
                >
                  {"Copyright 2023 \u00a9 Project Central. All Rights Reserved"}
                </div>
              </p.Stack>
              <div
                data-plasmic-name={"group717"}
                data-plasmic-override={overrides.group717}
                className={classNames(projectcss.all, sty.group717)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"buttonMedium"}
                  data-plasmic-override={overrides.buttonMedium}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.buttonMedium)}
                >
                  <_16OutlinedSuggestedSymbolPlusIcon
                    className={classNames(projectcss.all, sty.svg__usWex)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"button2"}
                    data-plasmic-override={overrides.button2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button2
                    )}
                  >
                    {"New Company"}
                  </div>
                  {false ? (
                    <IconsArrowRight26Icon
                      className={classNames(projectcss.all, sty.svg__mlJuq)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>
                <div
                  data-plasmic-name={"manageApplications4"}
                  data-plasmic-override={overrides.manageApplications4}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.manageApplications4
                  )}
                >
                  {"Companies"}
                </div>
                <div
                  data-plasmic-name={"vuesaxlinearmenu"}
                  data-plasmic-override={overrides.vuesaxlinearmenu}
                  className={classNames(projectcss.all, sty.vuesaxlinearmenu)}
                >
                  <div
                    data-plasmic-name={"vuesaxlinearmenu2"}
                    data-plasmic-override={overrides.vuesaxlinearmenu2}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearmenu2
                    )}
                  >
                    <FilterIcon
                      className={classNames(projectcss.all, sty.svg___7R7Sy)}
                      role={"img"}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"vuesaxlinearmenu3"}
                  data-plasmic-override={overrides.vuesaxlinearmenu3}
                  className={classNames(projectcss.all, sty.vuesaxlinearmenu3)}
                >
                  <div
                    data-plasmic-name={"vuesaxlinearmenu4"}
                    data-plasmic-override={overrides.vuesaxlinearmenu4}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearmenu4
                    )}
                  >
                    <CloseIcon
                      className={classNames(projectcss.all, sty.svg__t65Tt)}
                      role={"img"}
                    />
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"top2"}
                data-plasmic-override={overrides.top2}
                className={classNames(projectcss.all, sty.top2)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame36159"}
                  data-plasmic-override={overrides.frame36159}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame36159)}
                >
                  <div
                    data-plasmic-name={"group4004"}
                    data-plasmic-override={overrides.group4004}
                    className={classNames(projectcss.all, sty.group4004)}
                  >
                    <div
                      data-plasmic-name={"rectangle115"}
                      data-plasmic-override={overrides.rectangle115}
                      className={classNames(projectcss.all, sty.rectangle115)}
                    />

                    <div
                      data-plasmic-name={"frame36134"}
                      data-plasmic-override={overrides.frame36134}
                      className={classNames(projectcss.all, sty.frame36134)}
                    >
                      <div
                        data-plasmic-name={"helloSam"}
                        data-plasmic-override={overrides.helloSam}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.helloSam
                        )}
                      >
                        {"Hidden Brains Ltd."}
                      </div>
                      <div
                        data-plasmic-name={"helloSam2"}
                        data-plasmic-override={overrides.helloSam2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.helloSam2
                        )}
                      >
                        {"Admin"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"vuesaxlineararrowDown"}
                    data-plasmic-override={overrides.vuesaxlineararrowDown}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlineararrowDown
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxlineararrowDown2"}
                      data-plasmic-override={overrides.vuesaxlineararrowDown2}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxlineararrowDown2
                      )}
                    >
                      <ArrowDownIcon
                        className={classNames(projectcss.all, sty.svg___2RXm)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </p.Stack>
                {false ? (
                  <div
                    data-plasmic-name={"frame36137"}
                    data-plasmic-override={overrides.frame36137}
                    className={classNames(projectcss.all, sty.frame36137)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__psnG6)}
                      displayHeight={"34px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"34px"}
                      loading={"lazy"}
                      src={{
                        src: group4GtVffIgVaj,
                        fullWidth: 34,
                        fullHeight: 34,
                        aspectRatio: 1
                      }}
                    />

                    <AccessIcon
                      className={classNames(projectcss.all, sty.svg__jn8WU)}
                      role={"img"}
                    />

                    <ManagementIcon
                      className={classNames(projectcss.all, sty.svg__xa6LY)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames(projectcss.all, sty.logo)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame4017"}
                    data-plasmic-override={overrides.frame4017}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame4017)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__fPjOg)}
                      displayHeight={"30.226px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"34px"}
                      loading={"lazy"}
                      src={{
                        src: group5Miq1XqTfD,
                        fullWidth: 34,
                        fullHeight: 30.226,
                        aspectRatio: 1.096774
                      }}
                    />
                  </p.Stack>
                  <div
                    data-plasmic-name={"group4021"}
                    data-plasmic-override={overrides.group4021}
                    className={classNames(projectcss.all, sty.group4021)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wzF37
                      )}
                    >
                      {"Project"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xhThO
                      )}
                    >
                      {"Central"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"vuesaxlinearmenu5"}
                  data-plasmic-override={overrides.vuesaxlinearmenu5}
                  className={classNames(projectcss.all, sty.vuesaxlinearmenu5)}
                >
                  <div
                    data-plasmic-name={"vuesaxlinearmenu6"}
                    data-plasmic-override={overrides.vuesaxlinearmenu6}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearmenu6
                    )}
                  >
                    <MenuIcon
                      className={classNames(projectcss.all, sty.svg__cJpmj)}
                      role={"img"}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"vuesaxlinearmenu7"}
                  data-plasmic-override={overrides.vuesaxlinearmenu7}
                  className={classNames(projectcss.all, sty.vuesaxlinearmenu7)}
                />

                <IconsBellIcon
                  className={classNames(projectcss.all, sty.svg__jDaq4)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"vuesaxlinearmenu8"}
                  data-plasmic-override={overrides.vuesaxlinearmenu8}
                  className={classNames(projectcss.all, sty.vuesaxlinearmenu8)}
                >
                  <div
                    data-plasmic-name={"vuesaxlinearmenu9"}
                    data-plasmic-override={overrides.vuesaxlinearmenu9}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxlinearmenu9
                    )}
                  >
                    <CategoryIcon
                      className={classNames(projectcss.all, sty.svg__nmiRc)}
                      role={"img"}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"frame36160"}
                  data-plasmic-override={overrides.frame36160}
                  className={classNames(projectcss.all, sty.frame36160)}
                >
                  <div
                    data-plasmic-name={"group927"}
                    data-plasmic-override={overrides.group927}
                    className={classNames(projectcss.all, sty.group927)}
                  >
                    <div
                      data-plasmic-name={"rectangle5"}
                      data-plasmic-override={overrides.rectangle5}
                      className={classNames(projectcss.all, sty.rectangle5)}
                    />

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame19"}
                      data-plasmic-override={overrides.frame19}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame19)}
                    >
                      <div
                        data-plasmic-name={"iconlyLightSearch"}
                        data-plasmic-override={overrides.iconlyLightSearch}
                        className={classNames(
                          projectcss.all,
                          sty.iconlyLightSearch
                        )}
                      >
                        <SearchIcon
                          className={classNames(projectcss.all, sty.svg__kMHo)}
                          role={"img"}
                        />
                      </div>
                      <div
                        data-plasmic-name={"search"}
                        data-plasmic-override={overrides.search}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.search
                        )}
                      >
                        {"Type your keyword for quick search"}
                      </div>
                    </p.Stack>
                  </div>
                </div>
                <div
                  data-plasmic-name={"group4006"}
                  data-plasmic-override={overrides.group4006}
                  className={classNames(projectcss.all, sty.group4006)}
                >
                  <div
                    data-plasmic-name={"rectangle116"}
                    data-plasmic-override={overrides.rectangle116}
                    className={classNames(projectcss.all, sty.rectangle116)}
                  />

                  <div
                    data-plasmic-name={"search2"}
                    data-plasmic-override={overrides.search2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.search2
                    )}
                  >
                    {"All"}
                  </div>
                  <Vector3Icon
                    className={classNames(projectcss.all, sty.svg___5VhLc)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "companies",
    "list",
    "_6",
    "rectangle104",
    "vuesaxlinearaddCircle",
    "vuesaxlinearaddCircle2",
    "dataDisplayCheckbox",
    "group731",
    "rectangle117",
    "_24January2022",
    "_24January2023",
    "_24January2025",
    "_24January2024",
    "tagGreen",
    "live",
    "_5",
    "rectangle105",
    "vuesaxlinearaddCircle3",
    "vuesaxlinearaddCircle4",
    "dataDisplayCheckbox2",
    "group732",
    "rectangle110",
    "_24January2026",
    "_24January2027",
    "_24January2028",
    "_24January2029",
    "tagGreen2",
    "live2",
    "_4",
    "rectangle106",
    "dataDisplayCheckbox3",
    "group733",
    "rectangle111",
    "_24January2030",
    "_24January2031",
    "_24January2032",
    "_24January2033",
    "tagGreen3",
    "live3",
    "vuesaxlinearaddCircle5",
    "vuesaxlinearaddCircle6",
    "_3",
    "rectangle118",
    "vuesaxlinearaddCircle7",
    "vuesaxlinearaddCircle8",
    "dataDisplayCheckbox4",
    "group734",
    "rectangle112",
    "_24January2034",
    "_24January2035",
    "_24January2036",
    "_24January2037",
    "tagGreen4",
    "live4",
    "_2",
    "rectangle119",
    "vuesaxlinearaddCircle9",
    "vuesaxlinearaddCircle10",
    "_24January2038",
    "_24January2039",
    "_24January2040",
    "_24January2041",
    "tagGreen5",
    "live5",
    "_1",
    "rectangle113",
    "dataDisplayCheckbox5",
    "group735",
    "rectangle114",
    "_24January2042",
    "_24January2043",
    "_24January2044",
    "_24January2045",
    "frame36152",
    "tagBlue",
    "inventoryDemo",
    "tagBlue2",
    "inventoryDemo2",
    "tagBlue3",
    "inventoryDemo3",
    "tagBlue4",
    "tagBlue5",
    "inventoryDemo4",
    "secondaryButtonSmall",
    "button",
    "frame36247",
    "vuesaxlinearscroll",
    "tagGreen6",
    "live6",
    "vuesaxlinearminusCirlce",
    "vuesaxlinearminusCirlce2",
    "top",
    "rectangle103",
    "_24January2046",
    "_24January2047",
    "_24January2048",
    "_24January2049",
    "footer2",
    "group717",
    "buttonMedium",
    "button2",
    "manageApplications4",
    "vuesaxlinearmenu",
    "vuesaxlinearmenu2",
    "vuesaxlinearmenu3",
    "vuesaxlinearmenu4",
    "top2",
    "frame36159",
    "group4004",
    "rectangle115",
    "frame36134",
    "helloSam",
    "helloSam2",
    "vuesaxlineararrowDown",
    "vuesaxlineararrowDown2",
    "frame36137",
    "logo",
    "frame4017",
    "group4021",
    "vuesaxlinearmenu5",
    "vuesaxlinearmenu6",
    "vuesaxlinearmenu7",
    "vuesaxlinearmenu8",
    "vuesaxlinearmenu9",
    "frame36160",
    "group927",
    "rectangle5",
    "frame19",
    "iconlyLightSearch",
    "search",
    "group4006",
    "rectangle116",
    "search2"
  ],

  companies: [
    "companies",
    "list",
    "_6",
    "rectangle104",
    "vuesaxlinearaddCircle",
    "vuesaxlinearaddCircle2",
    "dataDisplayCheckbox",
    "group731",
    "rectangle117",
    "_24January2022",
    "_24January2023",
    "_24January2025",
    "_24January2024",
    "tagGreen",
    "live",
    "_5",
    "rectangle105",
    "vuesaxlinearaddCircle3",
    "vuesaxlinearaddCircle4",
    "dataDisplayCheckbox2",
    "group732",
    "rectangle110",
    "_24January2026",
    "_24January2027",
    "_24January2028",
    "_24January2029",
    "tagGreen2",
    "live2",
    "_4",
    "rectangle106",
    "dataDisplayCheckbox3",
    "group733",
    "rectangle111",
    "_24January2030",
    "_24January2031",
    "_24January2032",
    "_24January2033",
    "tagGreen3",
    "live3",
    "vuesaxlinearaddCircle5",
    "vuesaxlinearaddCircle6",
    "_3",
    "rectangle118",
    "vuesaxlinearaddCircle7",
    "vuesaxlinearaddCircle8",
    "dataDisplayCheckbox4",
    "group734",
    "rectangle112",
    "_24January2034",
    "_24January2035",
    "_24January2036",
    "_24January2037",
    "tagGreen4",
    "live4",
    "_2",
    "rectangle119",
    "vuesaxlinearaddCircle9",
    "vuesaxlinearaddCircle10",
    "_24January2038",
    "_24January2039",
    "_24January2040",
    "_24January2041",
    "tagGreen5",
    "live5",
    "_1",
    "rectangle113",
    "dataDisplayCheckbox5",
    "group735",
    "rectangle114",
    "_24January2042",
    "_24January2043",
    "_24January2044",
    "_24January2045",
    "frame36152",
    "tagBlue",
    "inventoryDemo",
    "tagBlue2",
    "inventoryDemo2",
    "tagBlue3",
    "inventoryDemo3",
    "tagBlue4",
    "tagBlue5",
    "inventoryDemo4",
    "secondaryButtonSmall",
    "button",
    "frame36247",
    "vuesaxlinearscroll",
    "tagGreen6",
    "live6",
    "vuesaxlinearminusCirlce",
    "vuesaxlinearminusCirlce2",
    "top",
    "rectangle103",
    "_24January2046",
    "_24January2047",
    "_24January2048",
    "_24January2049",
    "footer2",
    "group717",
    "buttonMedium",
    "button2",
    "manageApplications4",
    "vuesaxlinearmenu",
    "vuesaxlinearmenu2",
    "vuesaxlinearmenu3",
    "vuesaxlinearmenu4",
    "top2",
    "frame36159",
    "group4004",
    "rectangle115",
    "frame36134",
    "helloSam",
    "helloSam2",
    "vuesaxlineararrowDown",
    "vuesaxlineararrowDown2",
    "frame36137",
    "logo",
    "frame4017",
    "group4021",
    "vuesaxlinearmenu5",
    "vuesaxlinearmenu6",
    "vuesaxlinearmenu7",
    "vuesaxlinearmenu8",
    "vuesaxlinearmenu9",
    "frame36160",
    "group927",
    "rectangle5",
    "frame19",
    "iconlyLightSearch",
    "search",
    "group4006",
    "rectangle116",
    "search2"
  ],

  list: [
    "list",
    "_6",
    "rectangle104",
    "vuesaxlinearaddCircle",
    "vuesaxlinearaddCircle2",
    "dataDisplayCheckbox",
    "group731",
    "rectangle117",
    "_24January2022",
    "_24January2023",
    "_24January2025",
    "_24January2024",
    "tagGreen",
    "live",
    "_5",
    "rectangle105",
    "vuesaxlinearaddCircle3",
    "vuesaxlinearaddCircle4",
    "dataDisplayCheckbox2",
    "group732",
    "rectangle110",
    "_24January2026",
    "_24January2027",
    "_24January2028",
    "_24January2029",
    "tagGreen2",
    "live2",
    "_4",
    "rectangle106",
    "dataDisplayCheckbox3",
    "group733",
    "rectangle111",
    "_24January2030",
    "_24January2031",
    "_24January2032",
    "_24January2033",
    "tagGreen3",
    "live3",
    "vuesaxlinearaddCircle5",
    "vuesaxlinearaddCircle6",
    "_3",
    "rectangle118",
    "vuesaxlinearaddCircle7",
    "vuesaxlinearaddCircle8",
    "dataDisplayCheckbox4",
    "group734",
    "rectangle112",
    "_24January2034",
    "_24January2035",
    "_24January2036",
    "_24January2037",
    "tagGreen4",
    "live4",
    "_2",
    "rectangle119",
    "vuesaxlinearaddCircle9",
    "vuesaxlinearaddCircle10",
    "_24January2038",
    "_24January2039",
    "_24January2040",
    "_24January2041",
    "tagGreen5",
    "live5",
    "_1",
    "rectangle113",
    "dataDisplayCheckbox5",
    "group735",
    "rectangle114",
    "_24January2042",
    "_24January2043",
    "_24January2044",
    "_24January2045",
    "frame36152",
    "tagBlue",
    "inventoryDemo",
    "tagBlue2",
    "inventoryDemo2",
    "tagBlue3",
    "inventoryDemo3",
    "tagBlue4",
    "tagBlue5",
    "inventoryDemo4",
    "secondaryButtonSmall",
    "button",
    "frame36247",
    "vuesaxlinearscroll",
    "tagGreen6",
    "live6",
    "vuesaxlinearminusCirlce",
    "vuesaxlinearminusCirlce2"
  ],

  _6: [
    "_6",
    "rectangle104",
    "vuesaxlinearaddCircle",
    "vuesaxlinearaddCircle2",
    "dataDisplayCheckbox",
    "group731",
    "rectangle117",
    "_24January2022",
    "_24January2023",
    "_24January2025",
    "_24January2024",
    "tagGreen",
    "live"
  ],

  rectangle104: ["rectangle104"],
  vuesaxlinearaddCircle: ["vuesaxlinearaddCircle", "vuesaxlinearaddCircle2"],
  vuesaxlinearaddCircle2: ["vuesaxlinearaddCircle2"],
  dataDisplayCheckbox: ["dataDisplayCheckbox", "group731", "rectangle117"],
  group731: ["group731", "rectangle117"],
  rectangle117: ["rectangle117"],
  _24January2022: ["_24January2022"],
  _24January2023: ["_24January2023"],
  _24January2025: ["_24January2025"],
  _24January2024: ["_24January2024"],
  tagGreen: ["tagGreen", "live"],
  live: ["live"],
  _5: [
    "_5",
    "rectangle105",
    "vuesaxlinearaddCircle3",
    "vuesaxlinearaddCircle4",
    "dataDisplayCheckbox2",
    "group732",
    "rectangle110",
    "_24January2026",
    "_24January2027",
    "_24January2028",
    "_24January2029",
    "tagGreen2",
    "live2"
  ],

  rectangle105: ["rectangle105"],
  vuesaxlinearaddCircle3: ["vuesaxlinearaddCircle3", "vuesaxlinearaddCircle4"],
  vuesaxlinearaddCircle4: ["vuesaxlinearaddCircle4"],
  dataDisplayCheckbox2: ["dataDisplayCheckbox2", "group732", "rectangle110"],
  group732: ["group732", "rectangle110"],
  rectangle110: ["rectangle110"],
  _24January2026: ["_24January2026"],
  _24January2027: ["_24January2027"],
  _24January2028: ["_24January2028"],
  _24January2029: ["_24January2029"],
  tagGreen2: ["tagGreen2", "live2"],
  live2: ["live2"],
  _4: [
    "_4",
    "rectangle106",
    "dataDisplayCheckbox3",
    "group733",
    "rectangle111",
    "_24January2030",
    "_24January2031",
    "_24January2032",
    "_24January2033",
    "tagGreen3",
    "live3",
    "vuesaxlinearaddCircle5",
    "vuesaxlinearaddCircle6"
  ],

  rectangle106: ["rectangle106"],
  dataDisplayCheckbox3: ["dataDisplayCheckbox3", "group733", "rectangle111"],
  group733: ["group733", "rectangle111"],
  rectangle111: ["rectangle111"],
  _24January2030: ["_24January2030"],
  _24January2031: ["_24January2031"],
  _24January2032: ["_24January2032"],
  _24January2033: ["_24January2033"],
  tagGreen3: ["tagGreen3", "live3"],
  live3: ["live3"],
  vuesaxlinearaddCircle5: ["vuesaxlinearaddCircle5", "vuesaxlinearaddCircle6"],
  vuesaxlinearaddCircle6: ["vuesaxlinearaddCircle6"],
  _3: [
    "_3",
    "rectangle118",
    "vuesaxlinearaddCircle7",
    "vuesaxlinearaddCircle8",
    "dataDisplayCheckbox4",
    "group734",
    "rectangle112",
    "_24January2034",
    "_24January2035",
    "_24January2036",
    "_24January2037",
    "tagGreen4",
    "live4"
  ],

  rectangle118: ["rectangle118"],
  vuesaxlinearaddCircle7: ["vuesaxlinearaddCircle7", "vuesaxlinearaddCircle8"],
  vuesaxlinearaddCircle8: ["vuesaxlinearaddCircle8"],
  dataDisplayCheckbox4: ["dataDisplayCheckbox4", "group734", "rectangle112"],
  group734: ["group734", "rectangle112"],
  rectangle112: ["rectangle112"],
  _24January2034: ["_24January2034"],
  _24January2035: ["_24January2035"],
  _24January2036: ["_24January2036"],
  _24January2037: ["_24January2037"],
  tagGreen4: ["tagGreen4", "live4"],
  live4: ["live4"],
  _2: [
    "_2",
    "rectangle119",
    "vuesaxlinearaddCircle9",
    "vuesaxlinearaddCircle10",
    "_24January2038",
    "_24January2039",
    "_24January2040",
    "_24January2041",
    "tagGreen5",
    "live5"
  ],

  rectangle119: ["rectangle119"],
  vuesaxlinearaddCircle9: ["vuesaxlinearaddCircle9", "vuesaxlinearaddCircle10"],
  vuesaxlinearaddCircle10: ["vuesaxlinearaddCircle10"],
  _24January2038: ["_24January2038"],
  _24January2039: ["_24January2039"],
  _24January2040: ["_24January2040"],
  _24January2041: ["_24January2041"],
  tagGreen5: ["tagGreen5", "live5"],
  live5: ["live5"],
  _1: [
    "_1",
    "rectangle113",
    "dataDisplayCheckbox5",
    "group735",
    "rectangle114",
    "_24January2042",
    "_24January2043",
    "_24January2044",
    "_24January2045",
    "frame36152",
    "tagBlue",
    "inventoryDemo",
    "tagBlue2",
    "inventoryDemo2",
    "tagBlue3",
    "inventoryDemo3",
    "tagBlue4",
    "tagBlue5",
    "inventoryDemo4",
    "secondaryButtonSmall",
    "button",
    "frame36247",
    "vuesaxlinearscroll",
    "tagGreen6",
    "live6",
    "vuesaxlinearminusCirlce",
    "vuesaxlinearminusCirlce2"
  ],

  rectangle113: ["rectangle113"],
  dataDisplayCheckbox5: ["dataDisplayCheckbox5", "group735", "rectangle114"],
  group735: ["group735", "rectangle114"],
  rectangle114: ["rectangle114"],
  _24January2042: ["_24January2042"],
  _24January2043: ["_24January2043"],
  _24January2044: ["_24January2044"],
  _24January2045: ["_24January2045"],
  frame36152: [
    "frame36152",
    "tagBlue",
    "inventoryDemo",
    "tagBlue2",
    "inventoryDemo2",
    "tagBlue3",
    "inventoryDemo3",
    "tagBlue4",
    "tagBlue5",
    "inventoryDemo4",
    "secondaryButtonSmall",
    "button",
    "frame36247",
    "vuesaxlinearscroll"
  ],

  tagBlue: ["tagBlue", "inventoryDemo"],
  inventoryDemo: ["inventoryDemo"],
  tagBlue2: ["tagBlue2", "inventoryDemo2"],
  inventoryDemo2: ["inventoryDemo2"],
  tagBlue3: ["tagBlue3", "inventoryDemo3"],
  inventoryDemo3: ["inventoryDemo3"],
  tagBlue4: ["tagBlue4"],
  tagBlue5: ["tagBlue5", "inventoryDemo4"],
  inventoryDemo4: ["inventoryDemo4"],
  secondaryButtonSmall: ["secondaryButtonSmall", "button"],
  button: ["button"],
  frame36247: ["frame36247", "vuesaxlinearscroll"],
  vuesaxlinearscroll: ["vuesaxlinearscroll"],
  tagGreen6: ["tagGreen6", "live6"],
  live6: ["live6"],
  vuesaxlinearminusCirlce: [
    "vuesaxlinearminusCirlce",
    "vuesaxlinearminusCirlce2"
  ],

  vuesaxlinearminusCirlce2: ["vuesaxlinearminusCirlce2"],
  top: [
    "top",
    "rectangle103",
    "_24January2046",
    "_24January2047",
    "_24January2048",
    "_24January2049"
  ],

  rectangle103: ["rectangle103"],
  _24January2046: ["_24January2046"],
  _24January2047: ["_24January2047"],
  _24January2048: ["_24January2048"],
  _24January2049: ["_24January2049"],
  footer2: ["footer2"],
  group717: [
    "group717",
    "buttonMedium",
    "button2",
    "manageApplications4",
    "vuesaxlinearmenu",
    "vuesaxlinearmenu2",
    "vuesaxlinearmenu3",
    "vuesaxlinearmenu4"
  ],

  buttonMedium: ["buttonMedium", "button2"],
  button2: ["button2"],
  manageApplications4: ["manageApplications4"],
  vuesaxlinearmenu: ["vuesaxlinearmenu", "vuesaxlinearmenu2"],
  vuesaxlinearmenu2: ["vuesaxlinearmenu2"],
  vuesaxlinearmenu3: ["vuesaxlinearmenu3", "vuesaxlinearmenu4"],
  vuesaxlinearmenu4: ["vuesaxlinearmenu4"],
  top2: [
    "top2",
    "frame36159",
    "group4004",
    "rectangle115",
    "frame36134",
    "helloSam",
    "helloSam2",
    "vuesaxlineararrowDown",
    "vuesaxlineararrowDown2",
    "frame36137",
    "logo",
    "frame4017",
    "group4021",
    "vuesaxlinearmenu5",
    "vuesaxlinearmenu6",
    "vuesaxlinearmenu7",
    "vuesaxlinearmenu8",
    "vuesaxlinearmenu9",
    "frame36160",
    "group927",
    "rectangle5",
    "frame19",
    "iconlyLightSearch",
    "search",
    "group4006",
    "rectangle116",
    "search2"
  ],

  frame36159: [
    "frame36159",
    "group4004",
    "rectangle115",
    "frame36134",
    "helloSam",
    "helloSam2",
    "vuesaxlineararrowDown",
    "vuesaxlineararrowDown2"
  ],

  group4004: [
    "group4004",
    "rectangle115",
    "frame36134",
    "helloSam",
    "helloSam2"
  ],

  rectangle115: ["rectangle115"],
  frame36134: ["frame36134", "helloSam", "helloSam2"],
  helloSam: ["helloSam"],
  helloSam2: ["helloSam2"],
  vuesaxlineararrowDown: ["vuesaxlineararrowDown", "vuesaxlineararrowDown2"],
  vuesaxlineararrowDown2: ["vuesaxlineararrowDown2"],
  frame36137: ["frame36137"],
  logo: ["logo", "frame4017", "group4021"],
  frame4017: ["frame4017"],
  group4021: ["group4021"],
  vuesaxlinearmenu5: ["vuesaxlinearmenu5", "vuesaxlinearmenu6"],
  vuesaxlinearmenu6: ["vuesaxlinearmenu6"],
  vuesaxlinearmenu7: ["vuesaxlinearmenu7"],
  vuesaxlinearmenu8: ["vuesaxlinearmenu8", "vuesaxlinearmenu9"],
  vuesaxlinearmenu9: ["vuesaxlinearmenu9"],
  frame36160: [
    "frame36160",
    "group927",
    "rectangle5",
    "frame19",
    "iconlyLightSearch",
    "search"
  ],

  group927: [
    "group927",
    "rectangle5",
    "frame19",
    "iconlyLightSearch",
    "search"
  ],

  rectangle5: ["rectangle5"],
  frame19: ["frame19", "iconlyLightSearch", "search"],
  iconlyLightSearch: ["iconlyLightSearch"],
  search: ["search"],
  group4006: ["group4006", "rectangle116", "search2"],
  rectangle116: ["rectangle116"],
  search2: ["search2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCompanies__ArgProps,
          internalVariantPropNames: PlasmicCompanies__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCompanies__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompanies";
  } else {
    func.displayName = `PlasmicCompanies.${nodeName}`;
  }
  return func;
}

export const PlasmicCompanies = Object.assign(
  // Top-level PlasmicCompanies renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    companies: makeNodeComponent("companies"),
    list: makeNodeComponent("list"),
    _6: makeNodeComponent("_6"),
    rectangle104: makeNodeComponent("rectangle104"),
    vuesaxlinearaddCircle: makeNodeComponent("vuesaxlinearaddCircle"),
    vuesaxlinearaddCircle2: makeNodeComponent("vuesaxlinearaddCircle2"),
    dataDisplayCheckbox: makeNodeComponent("dataDisplayCheckbox"),
    group731: makeNodeComponent("group731"),
    rectangle117: makeNodeComponent("rectangle117"),
    _24January2022: makeNodeComponent("_24January2022"),
    _24January2023: makeNodeComponent("_24January2023"),
    _24January2025: makeNodeComponent("_24January2025"),
    _24January2024: makeNodeComponent("_24January2024"),
    tagGreen: makeNodeComponent("tagGreen"),
    live: makeNodeComponent("live"),
    _5: makeNodeComponent("_5"),
    rectangle105: makeNodeComponent("rectangle105"),
    vuesaxlinearaddCircle3: makeNodeComponent("vuesaxlinearaddCircle3"),
    vuesaxlinearaddCircle4: makeNodeComponent("vuesaxlinearaddCircle4"),
    dataDisplayCheckbox2: makeNodeComponent("dataDisplayCheckbox2"),
    group732: makeNodeComponent("group732"),
    rectangle110: makeNodeComponent("rectangle110"),
    _24January2026: makeNodeComponent("_24January2026"),
    _24January2027: makeNodeComponent("_24January2027"),
    _24January2028: makeNodeComponent("_24January2028"),
    _24January2029: makeNodeComponent("_24January2029"),
    tagGreen2: makeNodeComponent("tagGreen2"),
    live2: makeNodeComponent("live2"),
    _4: makeNodeComponent("_4"),
    rectangle106: makeNodeComponent("rectangle106"),
    dataDisplayCheckbox3: makeNodeComponent("dataDisplayCheckbox3"),
    group733: makeNodeComponent("group733"),
    rectangle111: makeNodeComponent("rectangle111"),
    _24January2030: makeNodeComponent("_24January2030"),
    _24January2031: makeNodeComponent("_24January2031"),
    _24January2032: makeNodeComponent("_24January2032"),
    _24January2033: makeNodeComponent("_24January2033"),
    tagGreen3: makeNodeComponent("tagGreen3"),
    live3: makeNodeComponent("live3"),
    vuesaxlinearaddCircle5: makeNodeComponent("vuesaxlinearaddCircle5"),
    vuesaxlinearaddCircle6: makeNodeComponent("vuesaxlinearaddCircle6"),
    _3: makeNodeComponent("_3"),
    rectangle118: makeNodeComponent("rectangle118"),
    vuesaxlinearaddCircle7: makeNodeComponent("vuesaxlinearaddCircle7"),
    vuesaxlinearaddCircle8: makeNodeComponent("vuesaxlinearaddCircle8"),
    dataDisplayCheckbox4: makeNodeComponent("dataDisplayCheckbox4"),
    group734: makeNodeComponent("group734"),
    rectangle112: makeNodeComponent("rectangle112"),
    _24January2034: makeNodeComponent("_24January2034"),
    _24January2035: makeNodeComponent("_24January2035"),
    _24January2036: makeNodeComponent("_24January2036"),
    _24January2037: makeNodeComponent("_24January2037"),
    tagGreen4: makeNodeComponent("tagGreen4"),
    live4: makeNodeComponent("live4"),
    _2: makeNodeComponent("_2"),
    rectangle119: makeNodeComponent("rectangle119"),
    vuesaxlinearaddCircle9: makeNodeComponent("vuesaxlinearaddCircle9"),
    vuesaxlinearaddCircle10: makeNodeComponent("vuesaxlinearaddCircle10"),
    _24January2038: makeNodeComponent("_24January2038"),
    _24January2039: makeNodeComponent("_24January2039"),
    _24January2040: makeNodeComponent("_24January2040"),
    _24January2041: makeNodeComponent("_24January2041"),
    tagGreen5: makeNodeComponent("tagGreen5"),
    live5: makeNodeComponent("live5"),
    _1: makeNodeComponent("_1"),
    rectangle113: makeNodeComponent("rectangle113"),
    dataDisplayCheckbox5: makeNodeComponent("dataDisplayCheckbox5"),
    group735: makeNodeComponent("group735"),
    rectangle114: makeNodeComponent("rectangle114"),
    _24January2042: makeNodeComponent("_24January2042"),
    _24January2043: makeNodeComponent("_24January2043"),
    _24January2044: makeNodeComponent("_24January2044"),
    _24January2045: makeNodeComponent("_24January2045"),
    frame36152: makeNodeComponent("frame36152"),
    tagBlue: makeNodeComponent("tagBlue"),
    inventoryDemo: makeNodeComponent("inventoryDemo"),
    tagBlue2: makeNodeComponent("tagBlue2"),
    inventoryDemo2: makeNodeComponent("inventoryDemo2"),
    tagBlue3: makeNodeComponent("tagBlue3"),
    inventoryDemo3: makeNodeComponent("inventoryDemo3"),
    tagBlue4: makeNodeComponent("tagBlue4"),
    tagBlue5: makeNodeComponent("tagBlue5"),
    inventoryDemo4: makeNodeComponent("inventoryDemo4"),
    secondaryButtonSmall: makeNodeComponent("secondaryButtonSmall"),
    button: makeNodeComponent("button"),
    frame36247: makeNodeComponent("frame36247"),
    vuesaxlinearscroll: makeNodeComponent("vuesaxlinearscroll"),
    tagGreen6: makeNodeComponent("tagGreen6"),
    live6: makeNodeComponent("live6"),
    vuesaxlinearminusCirlce: makeNodeComponent("vuesaxlinearminusCirlce"),
    vuesaxlinearminusCirlce2: makeNodeComponent("vuesaxlinearminusCirlce2"),
    top: makeNodeComponent("top"),
    rectangle103: makeNodeComponent("rectangle103"),
    _24January2046: makeNodeComponent("_24January2046"),
    _24January2047: makeNodeComponent("_24January2047"),
    _24January2048: makeNodeComponent("_24January2048"),
    _24January2049: makeNodeComponent("_24January2049"),
    footer2: makeNodeComponent("footer2"),
    group717: makeNodeComponent("group717"),
    buttonMedium: makeNodeComponent("buttonMedium"),
    button2: makeNodeComponent("button2"),
    manageApplications4: makeNodeComponent("manageApplications4"),
    vuesaxlinearmenu: makeNodeComponent("vuesaxlinearmenu"),
    vuesaxlinearmenu2: makeNodeComponent("vuesaxlinearmenu2"),
    vuesaxlinearmenu3: makeNodeComponent("vuesaxlinearmenu3"),
    vuesaxlinearmenu4: makeNodeComponent("vuesaxlinearmenu4"),
    top2: makeNodeComponent("top2"),
    frame36159: makeNodeComponent("frame36159"),
    group4004: makeNodeComponent("group4004"),
    rectangle115: makeNodeComponent("rectangle115"),
    frame36134: makeNodeComponent("frame36134"),
    helloSam: makeNodeComponent("helloSam"),
    helloSam2: makeNodeComponent("helloSam2"),
    vuesaxlineararrowDown: makeNodeComponent("vuesaxlineararrowDown"),
    vuesaxlineararrowDown2: makeNodeComponent("vuesaxlineararrowDown2"),
    frame36137: makeNodeComponent("frame36137"),
    logo: makeNodeComponent("logo"),
    frame4017: makeNodeComponent("frame4017"),
    group4021: makeNodeComponent("group4021"),
    vuesaxlinearmenu5: makeNodeComponent("vuesaxlinearmenu5"),
    vuesaxlinearmenu6: makeNodeComponent("vuesaxlinearmenu6"),
    vuesaxlinearmenu7: makeNodeComponent("vuesaxlinearmenu7"),
    vuesaxlinearmenu8: makeNodeComponent("vuesaxlinearmenu8"),
    vuesaxlinearmenu9: makeNodeComponent("vuesaxlinearmenu9"),
    frame36160: makeNodeComponent("frame36160"),
    group927: makeNodeComponent("group927"),
    rectangle5: makeNodeComponent("rectangle5"),
    frame19: makeNodeComponent("frame19"),
    iconlyLightSearch: makeNodeComponent("iconlyLightSearch"),
    search: makeNodeComponent("search"),
    group4006: makeNodeComponent("group4006"),
    rectangle116: makeNodeComponent("rectangle116"),
    search2: makeNodeComponent("search2"),
    // Metadata about props expected for PlasmicCompanies
    internalVariantProps: PlasmicCompanies__VariantProps,
    internalArgProps: PlasmicCompanies__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCompanies;
/* prettier-ignore-end */
